[package]
name = "glsweeper-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
gl = "0.14.0"
glfw = "0.51.0"
image = "0.24.5"
log = "0.4.17"
rand = "0.8.5"
