# .github/workflows/release.yml

name: release

on:
  release:
    types: [created]

jobs:
  release:
    permissions: write-all
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: "README.md LICENSE"
        run: chmod +x ci/github-actions/entrypoint.sh ci/github-actions/build.sh && ./ci/github-actions/entrypoint.sh
